import classes

songs = [
    classes.Song("Work From Home", "Fifth Harmony,Ty Dolla $ign", "7/27", classes.Duration(3, 44), "Pop", 2),
    classes.Song("Hello", "Adele", "25", classes.Duration(4, 55), "Pop", 1),
    classes.Song("The Box", "Roddy Ricch", "Please Excuse Me for Being Antisocial", classes.Duration(3, 16), "Rap", 2),
    classes.Song("Rockstar", "Post Malone,21 Savage", "Beerbongs & Bentleys", classes.Duration(3, 38), "Rap", 1),
    classes.Song("Industry Baby", "Lil Nas X,Jack Harlow", "Montero", classes.Duration(3, 32), "Rap", 1),
    classes.Song("No Role Modelz", "J. Cole", "2014 Forest Hills Drive", classes.Duration(4, 53), "Rap", 2),
    classes.Song("Stairway to Heaven", "Led Zeppelin", "Led Zeppelin IV", classes.Duration(8, 2), "Classic Rock", 1),
    classes.Song("Hotel California", "Eagles", "Hotel California", classes.Duration(6, 30), "Classic Rock", 1),
    classes.Song("Imagine", "John Lennon", "Imagine", classes.Duration(3, 3), "Classic Rock", 2),
    classes.Song("Smoke on the Water", "Deep Purple", "Machine Head", classes.Duration(5, 40), "Classic Rock", 3),
    classes.Song("Back in Black", "AC/DC", "Back in Black", classes.Duration(4, 15), "Classic Rock", 1),
    classes.Song("Bad Habits", "Ed Sheeran", "Equals", classes.Duration(3, 50), "Pop", 1),
    classes.Song("Shallow", "Lady Gaga,Bradley Cooper", "A Star Is Born", classes.Duration(3, 36), "Soundtrack", 2),
    classes.Song("Perfect", "Ed Sheeran", "Divide", classes.Duration(4, 23), "Pop",1),
    classes.Song("Livin' on a Prayer", "Bon Jovi", "Slippery When Wet", classes.Duration(4, 9), "Rock", 1),
    classes.Song("Poker Face", "Lady Gaga", "The Fame", classes.Duration(3, 57), "Pop", 1),
    classes.Song("We Will Rock You", "Queen", "News of the World", classes.Duration(2, 2), "Rock", 1),
    classes.Song("Don't Stop Believin'", "Journey", "Escape", classes.Duration(4, 11), "Rock", 1),
    classes.Song("Dancing Queen", "ABBA", "Arrival", classes.Duration(3, 51), "Pop", 1),
    classes.Song("We Are the Champions", "Queen", "News of the World", classes.Duration(3, 0), "Rock", 1),
    classes.Song("Super Bass", "Nicki Minaj", "Pink Friday", classes.Duration(3, 20), "Hip-Hop", 1),
    classes.Song("Take on Me", "A-ha", "Hunting High and Low", classes.Duration(3, 45), "Synth-pop", 1),
    classes.Song("Creep", "Radiohead", "Pablo Honey", classes.Duration(3, 56), "Alternative Rock", 1),
    classes.Song("Stayin' Alive", "Bee Gees", "Saturday Night Fever", classes.Duration(4, 45), "Disco", 1),
    classes.Song("Cheap Thrills", "Sia, Sean Paul", "This Is Acting", classes.Duration(3, 31), "Pop", 1),
    classes.Song("Somebody That I Used to Know", "Gotye, Kimbra", "Making Mirrors", classes.Duration(4, 5), "Alternative", 1),
    classes.Song("Bohemian Rhapsody", "Queen", "A Night at the Opera", classes.Duration(5, 55), "Classic Rock", 1),
    classes.Song("All Star", "Smash Mouth", "Astro Lounge", classes.Duration(3, 21), "Alternative Rock", 1),
    classes.Song("Counting Stars", "OneRepublic", "Native", classes.Duration(4, 17), "Pop", 1),
    classes.Song("I Will Always Love You", "Whitney Houston", "The Bodyguard Soundtrack", classes.Duration(4, 31), "Pop", 1),
    classes.Song("Can't Stop the Feeling!", "Justin Timberlake", "Trolls Soundtrack", classes.Duration(3, 56), "Pop", 1),
    classes.Song("Sweet Home Alabama", "Lynyrd Skynyrd", "Second Helping", classes.Duration(4, 45), "Classic Rock", 1),
    classes.Song("Born to Run", "Bruce Springsteen", "Born to Run", classes.Duration(4, 30), "Classic Rock", 1),
    classes.Song("Take Me Home, Country Roads", "John Denver", "Poems, Prayers & Promises", classes.Duration(3, 10), "Country", 1),
    classes.Song("Boulevard of Broken Dreams", "Green Day", "American Idiot", classes.Duration(4, 20), "Alternative Rock", 1),
    classes.Song("Dream On", "Aerosmith", "Aerosmith", classes.Duration(4, 28), "Classic Rock", 1),
    classes.Song("Summer of '69", "Bryan Adams", "Reckless", classes.Duration(3, 36), "Rock", 1),
    classes.Song("Wonderwall", "Oasis", "(What's the Story) Morning Glory?", classes.Duration(4, 18), "Britpop", 1),
    classes.Song("Smells Like Teen Spirit", "Nirvana", "Nevermind", classes.Duration(5, 1), "Grunge", 1),
    classes.Song("Seven Nation Army", "The White Stripes", "Elephant", classes.Duration(3, 52), "Alternative Rock", 1),
    classes.Song("Hallelujah", "Jeff Buckley", "Grace", classes.Duration(6, 53), "Alternative", 1),
    classes.Song("Mr. Brightside", "The Killers", "Hot Fuss", classes.Duration(3, 43), "Alternative Rock", 1),
    classes.Song("Heroes", "David Bowie", "Heroes", classes.Duration(6, 7), "Rock", 1),
    classes.Song("Sweet Child O' Mine", "Guns N' Roses", "Appetite for Destruction", classes.Duration(5, 56), "Classic Rock", 1),
    classes.Song("I Wanna Dance with Somebody", "Whitney Houston", "Whitney", classes.Duration(4, 51), "Pop", 1),
    classes.Song("California Love", "2Pac, Dr. Dre", "All Eyez on Me", classes.Duration(5, 46), "Hip-Hop", 1),
    classes.Song("Iris", "Goo Goo Dolls", "Dizzy Up the Girl", classes.Duration(4, 50), "Alternative Rock", 1),
    classes.Song("Africa", "Toto", "Toto IV", classes.Duration(4, 55), "Rock", 1),
    classes.Song("Eye of the Tiger", "Survivor", "Rocky III Soundtrack", classes.Duration(4, 5), "Rock", 1),
    classes.Song("Riptide", "Vance Joy", "Dream Your Life Away", classes.Duration(3, 24), "Indie", 1),
    classes.Song("Chasing Cars", "Snow Patrol", "Eyes Open", classes.Duration(4, 27), "Alternative Rock", 1),
    classes.Song("American Idiot", "Green Day", "American Idiot", classes.Duration(2, 54), "Punk Rock", 1),
    classes.Song("Lose Yourself", "Eminem", "8 Mile Soundtrack", classes.Duration(5, 20), "Hip-Hop", 1),
    classes.Song("Clocks", "Coldplay", "A Rush of Blood to the Head", classes.Duration(5, 7), "Alternative Rock", 1),
    classes.Song("Wake Me Up", "Avicii", "True", classes.Duration(4, 7), "Electronic", 1),
    classes.Song("The Sound of Silence", "Simon & Garfunkel", "Wednesday Morning, 3 A.M.", classes.Duration(3, 5), "Folk Rock", 1),
    classes.Song("Paint It Black", "The Rolling Stones", "Aftermath", classes.Duration(3, 22), "Rock", 1),
    classes.Song("Lose Control", "Teddy Swims", "Lose Control", classes.Duration(3, 30), "Pop", 1),
    classes.Song("Espresso", "Sabrina Carpenter", "Espresso", classes.Duration(2, 50), "Pop", 1),
    classes.Song("I Had Some Help", "Post Malone, Morgan Wallen", "I Had Some Help", classes.Duration(3, 20), "Country", 1),
    classes.Song("Too Sweet", "Hozier", "Unreal Unearth", classes.Duration(4, 10), "Alternative", 1),
    classes.Song("Greedy", "Tate McRae", "Greedy", classes.Duration(2, 45), "Pop", 1),
    classes.Song("Paint the Town Red", "Doja Cat", "Scarlet", classes.Duration(3, 51), "Hip-Hop", 1),
    classes.Song("Fortnight", "Taylor Swift, Post Malone", "The Tortured Poets Department", classes.Duration(3, 45), "Pop", 1),
    classes.Song("Birds of a Feather", "Billie Eilish", "Hit Me Hard and Soft", classes.Duration(3, 55), "Pop", 1),
    classes.Song("Million Dollar Baby", "Tommy Richman", "Million Dollar Baby", classes.Duration(3, 10), "Pop", 1),
    classes.Song("Good Luck, Babe!", "Chappell Roan", "Good Luck, Babe!", classes.Duration(3, 40), "Pop", 1),
    classes.Song("Saturn", "SZA", "Saturn", classes.Duration(3, 30), "R&B", 1),
    classes.Song("Fast Car", "Luke Combs", "Fast Car", classes.Duration(4, 0), "Country", 1),
    classes.Song("Water", "Tyla", "Tyla", classes.Duration(3, 20), "Afrobeats", 1),
    classes.Song("Feather", "Sabrina Carpenter", "Feather", classes.Duration(2, 55), "Pop", 1),
    classes.Song("Not Like Us", "Kendrick Lamar", "Not Like Us", classes.Duration(4, 30), "Hip-Hop", 1),
    classes.Song("Please Please Please", "Sabrina Carpenter", "Please Please Please", classes.Duration(3, 15), "Pop", 1),
    classes.Song("Agora Hills", "Doja Cat", "Scarlet", classes.Duration(4, 20), "Hip-Hop", 1),
    classes.Song("I Remember Everything", "Zach Bryan, Kacey Musgraves", "I Remember Everything", classes.Duration(3, 50), "Country", 1),
    classes.Song("Lovin on Me", "Jack Harlow", "Lovin on Me", classes.Duration(2, 30), "Hip-Hop", 1),
    classes.Song("Thinkin' Bout Me", "Morgan Wallen", "Thinkin' Bout Me", classes.Duration(3, 45), "Country", 1),
    classes.Song("Hey Jude", "The Beatles", "Hey Jude", classes.Duration(7, 11), "Rock", 1),
    classes.Song("Let It Be", "The Beatles", "Let It Be", classes.Duration(4, 3), "Rock", 1),
    classes.Song("Yesterday", "The Beatles", "Help!", classes.Duration(2, 5), "Rock", 1),
    classes.Song("Come Together", "The Beatles", "Abbey Road", classes.Duration(4, 19), "Rock", 1),
    classes.Song("Something", "The Beatles", "Abbey Road", classes.Duration(3, 3), "Rock", 1),
    classes.Song("A Hard Day's Night", "The Beatles", "A Hard Day's Night", classes.Duration(2, 34), "Rock", 1),
    classes.Song("Help!", "The Beatles", "Help!", classes.Duration(2, 18), "Rock", 1),
    classes.Song("Twist and Shout", "The Beatles", "Please Please Me", classes.Duration(2, 33), "Rock", 1),
    classes.Song("I Want to Hold Your Hand", "The Beatles", "Meet The Beatles!", classes.Duration(2, 24), "Rock", 1),
    classes.Song("Penny Lane", "The Beatles", "Magical Mystery Tour", classes.Duration(3, 0), "Rock", 1),
    classes.Song("Eleanor Rigby", "The Beatles", "Revolver", classes.Duration(2, 6), "Rock", 1),
    classes.Song("Lucy in the Sky with Diamonds", "The Beatles", "Sgt. Pepper's Lonely Hearts Club Band", classes.Duration(3, 28), "Rock", 1),
    classes.Song("Strawberry Fields Forever", "The Beatles", "Magical Mystery Tour", classes.Duration(4, 10), "Rock", 1),
    classes.Song("Blackbird", "The Beatles", "The White Album", classes.Duration(2, 18), "Rock", 1),
    classes.Song("Here Comes the Sun", "The Beatles", "Abbey Road", classes.Duration(3, 5), "Rock", 1),
    classes.Song("While My Guitar Gently Weeps", "The Beatles", "The White Album", classes.Duration(4, 45), "Rock", 1),
    classes.Song("All You Need Is Love", "The Beatles", "Magical Mystery Tour", classes.Duration(3, 48), "Rock", 1),
    classes.Song("Can't Buy Me Love", "The Beatles", "A Hard Day's Night", classes.Duration(2, 11), "Rock", 1),
    classes.Song("Love Me Do", "The Beatles", "Please Please Me", classes.Duration(2, 21), "Rock", 1),
    classes.Song("Yellow Submarine", "The Beatles", "Revolver", classes.Duration(2, 38), "Rock", 1),
    classes.Song("Billie Jean", "Michael Jackson", "Thriller", classes.Duration(4, 54), "Pop", 1),
    classes.Song("Thriller", "Michael Jackson", "Thriller", classes.Duration(5, 57), "Pop", 1),
    classes.Song("Beat It", "Michael Jackson", "Thriller", classes.Duration(4, 18), "Pop", 1),
    classes.Song("Smooth Criminal", "Michael Jackson", "Bad", classes.Duration(4, 17), "Pop", 1),
    classes.Song("Black or White", "Michael Jackson", "Dangerous", classes.Duration(4, 16), "Pop", 1),
    classes.Song("Man in the Mirror", "Michael Jackson", "Bad", classes.Duration(5, 19), "Pop", 1),
    classes.Song("Don't Stop 'Til You Get Enough", "Michael Jackson", "Off the Wall", classes.Duration(6, 5), "Pop", 1),
    classes.Song("Rock With You", "Michael Jackson", "Off the Wall", classes.Duration(3, 40), "Pop", 1),
    classes.Song("The Way You Make Me Feel", "Michael Jackson", "Bad", classes.Duration(4, 58), "Pop", 1),
    classes.Song("Bad", "Michael Jackson", "Bad", classes.Duration(4, 7), "Pop", 1),
    classes.Song("Wanna Be Startin' Somethin'", "Michael Jackson", "Thriller", classes.Duration(6, 3), "Pop", 1),
    classes.Song("You Are Not Alone", "Michael Jackson", "HIStory: Past, Present and Future, Book I", classes.Duration(5, 45), "Pop", 1),
    classes.Song("Remember the Time", "Michael Jackson", "Dangerous", classes.Duration(4, 0), "Pop", 1),
    classes.Song("Heal the World", "Michael Jackson", "Dangerous", classes.Duration(6, 25), "Pop", 1),
    classes.Song("Earth Song", "Michael Jackson", "HIStory: Past, Present and Future, Book I", classes.Duration(6, 46), "Pop", 1),
    classes.Song("Dirty Diana", "Michael Jackson", "Bad", classes.Duration(4, 42), "Pop", 1),
    classes.Song("They Don't Care About Us", "Michael Jackson", "HIStory: Past, Present and Future, Book I", classes.Duration(4, 44), "Pop", 1),
    classes.Song("Give In to Me", "Michael Jackson", "Dangerous", classes.Duration(5, 30), "Pop", 1),
    classes.Song("Blood on the Dance Floor", "Michael Jackson", "Blood on the Dance Floor: HIStory in the Mix", classes.Duration(4, 13), "Pop", 1),
    classes.Song("Leave Me Alone", "Michael Jackson", "Bad", classes.Duration(4, 40), "Pop", 1),
    classes.Song("Jailhouse Rock", "Elvis Presley", "Jailhouse Rock", classes.Duration(2, 30), "Rock", 1),
    classes.Song("Can't Help Falling in Love", "Elvis Presley", "Blue Hawaii", classes.Duration(3, 0), "Rock", 1),
    classes.Song("Hound Dog", "Elvis Presley", "Elvis Presley", classes.Duration(2, 15), "Rock", 1),
    classes.Song("Suspicious Minds", "Elvis Presley", "From Elvis in Memphis", classes.Duration(4, 22), "Rock", 1),
    classes.Song("Love Me Tender", "Elvis Presley", "Love Me Tender", classes.Duration(2, 45), "Rock", 1),
    classes.Song("Blue Suede Shoes", "Elvis Presley", "Elvis Presley", classes.Duration(2, 0), "Rock", 1),
    classes.Song("Heartbreak Hotel", "Elvis Presley", "Elvis Presley", classes.Duration(2, 8), "Rock", 1),
    classes.Song("All Shook Up", "Elvis Presley", "Elvis' Golden Records", classes.Duration(1, 57), "Rock", 1),
    classes.Song("Burning Love", "Elvis Presley", "Burning Love and Hits from His Movies", classes.Duration(2, 50), "Rock", 1),
    classes.Song("Don't Be Cruel", "Elvis Presley", "Elvis Presley", classes.Duration(2, 3), "Rock", 1),
    classes.Song("Return to Sender", "Elvis Presley", "Girls! Girls! Girls!", classes.Duration(2, 9), "Rock", 1),
    classes.Song("In the Ghetto", "Elvis Presley", "From Elvis in Memphis", classes.Duration(2, 57), "Rock", 1),
    classes.Song("A Little Less Conversation", "Elvis Presley", "Almost in Love", classes.Duration(2, 38), "Rock", 1),
    classes.Song("That's All Right", "Elvis Presley", "Elvis Presley", classes.Duration(1, 57), "Rock", 1),
    classes.Song("Are You Lonesome Tonight?", "Elvis Presley", "Elvis' Golden Records", classes.Duration(3, 8), "Rock", 1),
    classes.Song("It's Now or Never", "Elvis Presley", "Elvis Presley", classes.Duration(3, 15), "Rock", 1),
    classes.Song("Kentucky Rain", "Elvis Presley", "Elvis Presley", classes.Duration(3, 20), "Rock", 1),
    classes.Song("Viva Las Vegas", "Elvis Presley", "Viva Las Vegas", classes.Duration(2, 24), "Rock", 1),
    classes.Song("Always on My Mind", "Elvis Presley", "Separate Ways", classes.Duration(3, 38), "Rock", 1),
    classes.Song("Moody Blue", "Elvis Presley", "Moody Blue", classes.Duration(2, 49), "Rock", 1),
    classes.Song("Crazy in Love", "Beyoncé, Jay-Z", "Dangerously in Love", classes.Duration(3, 56), "R&B", 1),
    classes.Song("Halo", "Beyoncé", "I Am... Sasha Fierce", classes.Duration(4, 21), "Pop", 1),
    classes.Song("Single Ladies (Put a Ring on It)", "Beyoncé", "I Am... Sasha Fierce", classes.Duration(3, 13), "Pop", 1),
    classes.Song("Irreplaceable", "Beyoncé", "B'Day", classes.Duration(3, 47), "R&B", 1),
    classes.Song("Drunk in Love", "Beyoncé, Jay-Z", "Beyoncé", classes.Duration(5, 23), "R&B", 1),
    classes.Song("Love on Top", "Beyoncé", "4", classes.Duration(4, 27), "R&B", 1),
    classes.Song("Formation", "Beyoncé", "Lemonade", classes.Duration(3, 26), "Hip-Hop", 1),
    classes.Song("Run the World (Girls)", "Beyoncé", "4", classes.Duration(3, 56), "Pop", 1),
    classes.Song("Partition", "Beyoncé", "Beyoncé", classes.Duration(5, 19), "R&B", 1),
    classes.Song("If I Were a Boy", "Beyoncé", "I Am... Sasha Fierce", classes.Duration(4, 10), "Pop", 1),
    classes.Song("Best Thing I Never Had", "Beyoncé", "4", classes.Duration(4, 13), "R&B", 1),
    classes.Song("XO", "Beyoncé", "Beyoncé", classes.Duration(3, 36), "Pop", 1),
    classes.Song("Sweet Dreams", "Beyoncé", "I Am... Sasha Fierce", classes.Duration(3, 28), "Pop", 1),
    classes.Song("Diva", "Beyoncé", "I Am... Sasha Fierce", classes.Duration(3, 20), "Hip-Hop", 1),
    classes.Song("Countdown", "Beyoncé", "4", classes.Duration(3, 33), "R&B", 1),
    classes.Song("Pretty Hurts", "Beyoncé", "Beyoncé", classes.Duration(4, 17), "Pop", 1),
    classes.Song("Flawless", "Beyoncé, Chimamanda Ngozi Adichie", "Beyoncé", classes.Duration(4, 10), "Hip-Hop", 1),
    classes.Song("Dangerously in Love 2", "Beyoncé", "Dangerously in Love", classes.Duration(4, 53), "R&B", 1),
    classes.Song("Me, Myself and I", "Beyoncé", "Dangerously in Love", classes.Duration(5, 1), "R&B", 1),
    classes.Song("Cuff It", "Beyoncé", "Renaissance", classes.Duration(3, 45), "R&B", 1),
    classes.Song("Willow", "Taylor Swift", "Evermore", classes.Duration(3, 34), "Indie Pop", 1),
    classes.Song("Karma", "Taylor Swift", "Midnights", classes.Duration(3, 24), "Pop", 1),
    classes.Song("Enchanted", "Taylor Swift", "Speak Now", classes.Duration(5, 52), "Pop", 1),
    classes.Song("Love Story", "Taylor Swift", "Fearless", classes.Duration(3, 55), "Pop", 1),
    classes.Song("You Belong with Me", "Taylor Swift", "Fearless", classes.Duration(3, 52), "Pop", 1),
    classes.Song("Blank Space", "Taylor Swift", "1989", classes.Duration(3, 51), "Pop", 1),
    classes.Song("Shake It Off", "Taylor Swift", "1989", classes.Duration(3, 39), "Pop", 1),
    classes.Song("All Too Well", "Taylor Swift", "Red", classes.Duration(5, 29), "Pop", 1),
    classes.Song("Style", "Taylor Swift", "1989", classes.Duration(3, 51), "Pop", 1),
    classes.Song("Bad Blood", "Taylor Swift, Kendrick Lamar", "1989", classes.Duration(3, 31), "Pop", 1),
    classes.Song("Wildest Dreams", "Taylor Swift", "1989", classes.Duration(3, 40), "Pop", 1),
    classes.Song("Delicate", "Taylor Swift", "Reputation", classes.Duration(3, 52), "Pop", 1),
    classes.Song("The Archer", "Taylor Swift", "Lover", classes.Duration(3, 31), "Pop", 1),
    classes.Song("Cardigan", "Taylor Swift", "Folklore", classes.Duration(3, 59), "Indie Pop", 1),
    classes.Song("Anti-Hero", "Taylor Swift", "Midnights", classes.Duration(3, 20), "Pop", 1),
    classes.Song("The Man", "Taylor Swift", "Lover", classes.Duration(3, 10), "Pop", 1),
    classes.Song("Back to December", "Taylor Swift", "Speak Now", classes.Duration(4, 54), "Pop", 1),
    classes.Song("Mean", "Taylor Swift", "Speak Now", classes.Duration(3, 57), "Country", 1),
    classes.Song("No Woman, No Cry", "Bob Marley & The Wailers", "Natty Dread", classes.Duration(7, 8), "Reggae", 1),
    classes.Song("Three Little Birds", "Bob Marley & The Wailers", "Exodus", classes.Duration(3, 0), "Reggae", 1),
    classes.Song("Buffalo Soldier", "Bob Marley & The Wailers", "Confrontation", classes.Duration(4, 16), "Reggae", 1),
    classes.Song("One Love", "Bob Marley & The Wailers", "Exodus", classes.Duration(2, 54), "Reggae", 1),
    classes.Song("Redemption Song", "Bob Marley & The Wailers", "Uprising", classes.Duration(3, 55), "Reggae", 1),
    classes.Song("Jamming", "Bob Marley & The Wailers", "Exodus", classes.Duration(3, 31), "Reggae", 1),
    classes.Song("Is This Love", "Bob Marley & The Wailers", "Kaya", classes.Duration(3, 52), "Reggae", 1),
    classes.Song("Could You Be Loved", "Bob Marley & The Wailers", "Uprising", classes.Duration(3, 57), "Reggae", 1),
    classes.Song("Get Up, Stand Up", "Bob Marley & The Wailers", "Burnin'", classes.Duration(3, 16), "Reggae", 1),
    classes.Song("Waiting in Vain", "Bob Marley & The Wailers", "Exodus", classes.Duration(4, 16), "Reggae", 1),
    classes.Song("Stir It Up", "Bob Marley & The Wailers", "Catch a Fire", classes.Duration(5, 32), "Reggae", 1),
    classes.Song("I Shot the Sheriff", "Bob Marley & The Wailers", "Burnin'", classes.Duration(4, 41), "Reggae", 1),
    classes.Song("Sun Is Shining", "Bob Marley & The Wailers", "Kaya", classes.Duration(4, 58), "Reggae", 1),
    classes.Song("Easy Skanking", "Bob Marley & The Wailers", "Kaya", classes.Duration(2, 56), "Reggae", 1),
    classes.Song("Concrete Jungle", "Bob Marley & The Wailers", "Catch a Fire", classes.Duration(4, 13), "Reggae", 1),
    classes.Song("Lively Up Yourself", "Bob Marley & The Wailers", "Natty Dread", classes.Duration(5, 11), "Reggae", 1),
    classes.Song("So Much Trouble in the World", "Bob Marley & The Wailers", "Survival", classes.Duration(3, 57), "Reggae", 1),
    classes.Song("Punky Reggae Party", "Bob Marley & The Wailers", "Exodus", classes.Duration(6, 50), "Reggae", 1),
    classes.Song("Roots, Rock, Reggae", "Bob Marley & The Wailers", "Rastaman Vibration", classes.Duration(3, 38), "Reggae", 1),
    classes.Song("Turn Your Lights Down Low", "Bob Marley & The Wailers", "Exodus", classes.Duration(3, 39), "Reggae", 1),
    classes.Song("Like a Virgin", "Madonna", "Like a Virgin", classes.Duration(3, 38), "Pop", 1),
    classes.Song("Material Girl", "Madonna", "Like a Virgin", classes.Duration(4, 0), "Pop", 1),
    classes.Song("Vogue", "Madonna", "I'm Breathless", classes.Duration(5, 0), "Pop", 1),
    classes.Song("Like a Prayer", "Madonna", "Like a Prayer", classes.Duration(5, 38), "Pop", 1),
    classes.Song("Hung Up", "Madonna", "Confessions on a Dance Floor", classes.Duration(5, 37), "Pop", 1),
    classes.Song("Into the Groove", "Madonna", "Desperately Seeking Susan Soundtrack", classes.Duration(4, 45), "Pop", 1),
    classes.Song("Frozen", "Madonna", "Ray of Light", classes.Duration(6, 12), "Pop", 1),
    classes.Song("Papa Don't Preach", "Madonna", "True Blue", classes.Duration(4, 29), "Pop", 1),
    classes.Song("Express Yourself", "Madonna", "Like a Prayer", classes.Duration(4, 39), "Pop", 1),
    classes.Song("Ray of Light", "Madonna", "Ray of Light", classes.Duration(5, 20), "Pop", 1),
    classes.Song("Live to Tell", "Madonna", "True Blue", classes.Duration(5, 51), "Pop", 1),
    classes.Song("Borderline", "Madonna", "Madonna", classes.Duration(5, 18), "Pop", 1),
    classes.Song("Open Your Heart", "Madonna", "True Blue", classes.Duration(4, 12), "Pop", 1),
    classes.Song("La Isla Bonita", "Madonna", "True Blue", classes.Duration(4, 18), "Pop", 1),
    classes.Song("Holiday", "Madonna", "Madonna", classes.Duration(6, 8), "Pop", 1),
    classes.Song("Music", "Madonna", "Music", classes.Duration(3, 44), "Pop", 1),
    classes.Song("Take a Bow", "Madonna", "Bedtime Stories", classes.Duration(5, 21), "Pop", 1),
    classes.Song("Cherish", "Madonna", "Like a Prayer", classes.Duration(5, 3), "Pop", 1),
    classes.Song("Lucky Star", "Madonna", "Madonna", classes.Duration(5, 37), "Pop", 1),
    classes.Song("True Blue", "Madonna", "True Blue", classes.Duration(4, 2), "Pop", 1),
    classes.Song("Bad Guy", "Billie Eilish", "When We All Fall Asleep, Where Do We Go?", classes.Duration(3, 14), "Pop", 1),
    classes.Song("Happier Than Ever", "Billie Eilish", "Happier Than Ever", classes.Duration(4, 58), "Pop", 1),
    classes.Song("Everything I Wanted", "Billie Eilish", "Everything I Wanted", classes.Duration(4, 5), "Pop", 1),
    classes.Song("Ocean Eyes", "Billie Eilish", "Ocean Eyes", classes.Duration(3, 20), "Pop", 1),
    classes.Song("Bury a Friend", "Billie Eilish", "When We All Fall Asleep, Where Do We Go?", classes.Duration(3, 13), "Pop", 1),
    classes.Song("Lovely", "Billie Eilish, Khalid", "Lovely", classes.Duration(3, 21), "Pop", 1),
    classes.Song("You Should See Me in a Crown", "Billie Eilish", "When We All Fall Asleep, Where Do We Go?", classes.Duration(3, 1), "Pop", 1),
    classes.Song("Your Power", "Billie Eilish", "Happier Than Ever", classes.Duration(4, 5), "Pop", 1),
    classes.Song("I Love You", "Billie Eilish", "When We All Fall Asleep, Where Do We Go?", classes.Duration(4, 51), "Pop", 1),
    classes.Song("Bellyache", "Billie Eilish", "Don't Smile at Me", classes.Duration(3, 30), "Pop", 1),
    classes.Song("My Future", "Billie Eilish", "My Future", classes.Duration(3, 28), "Pop", 1),
    classes.Song("Lost Cause", "Billie Eilish", "Happier Than Ever", classes.Duration(3, 32), "Pop", 1),
    classes.Song("No Time to Die", "Billie Eilish", "No Time to Die", classes.Duration(4, 2), "Pop", 1),
    classes.Song("Therefore I Am", "Billie Eilish", "Therefore I Am", classes.Duration(2, 54), "Pop", 1),
    classes.Song("TV", "Billie Eilish", "Guitar Songs", classes.Duration(4, 14), "Pop", 1),
    classes.Song("Male Fantasy", "Billie Eilish", "Happier Than Ever", classes.Duration(3, 14), "Pop", 1),
    classes.Song("Six Feet Under", "Billie Eilish", "Six Feet Under", classes.Duration(3, 9), "Pop", 1),
    classes.Song("Copycat", "Billie Eilish", "Don't Smile at Me", classes.Duration(3, 13), "Pop", 1),
    classes.Song("Watch", "Billie Eilish", "Don't Smile at Me", classes.Duration(2, 57), "Pop", 1),
    classes.Song("Getting Older", "Billie Eilish", "Happier Than Ever", classes.Duration(4, 4), "Pop", 1),
    classes.Song("Blinding Lights", "The Weeknd", "After Hours", classes.Duration(3, 20), "Pop", 1),
    classes.Song("Save Your Tears", "The Weeknd", "After Hours", classes.Duration(3, 35), "Pop", 1),
    classes.Song("Starboy", "The Weeknd, Daft Punk", "Starboy", classes.Duration(3, 50), "Pop", 1),
    classes.Song("The Hills", "The Weeknd", "Beauty Behind the Madness", classes.Duration(4, 2), "R&B", 1),
    classes.Song("I Feel It Coming", "The Weeknd, Daft Punk", "Starboy", classes.Duration(4, 29), "Pop", 1),
    classes.Song("Die For You", "The Weeknd", "Starboy", classes.Duration(4, 20), "R&B", 1),
    classes.Song("Call Out My Name", "The Weeknd", "My Dear Melancholy,", classes.Duration(3, 48), "R&B", 1),
    classes.Song("Earned It", "The Weeknd", "Fifty Shades of Grey Soundtrack", classes.Duration(4, 37), "R&B", 1),
    classes.Song("Can't Feel My Face", "The Weeknd", "Beauty Behind the Madness", classes.Duration(3, 33), "Pop", 1),
    classes.Song("Out of Time", "The Weeknd", "Dawn FM", classes.Duration(3, 34), "Pop", 1),
    classes.Song("Sacrifice", "The Weeknd", "Dawn FM", classes.Duration(3, 9), "Pop", 1),
    classes.Song("Gasoline", "The Weeknd", "Dawn FM", classes.Duration(3, 32), "Pop", 1),
    classes.Song("Is There Someone Else?", "The Weeknd", "Dawn FM", classes.Duration(3, 19), "Pop", 1),
    classes.Song("Less Than Zero", "The Weeknd", "Dawn FM", classes.Duration(3, 31), "Pop", 1),
    classes.Song("Reminder", "The Weeknd", "Starboy", classes.Duration(3, 38), "R&B", 1),
    classes.Song("Pray For Me", "The Weeknd, Kendrick Lamar", "Black Panther Soundtrack", classes.Duration(3, 31), "Hip-Hop", 1),
    classes.Song("Lost in the Fire", "Gesaffelstein, The Weeknd", "Hyperion", classes.Duration(3, 22), "Electronic", 1),
    classes.Song("Heartless", "The Weeknd", "After Hours", classes.Duration(3, 18), "R&B", 1),
    classes.Song("In Your Eyes", "The Weeknd", "After Hours", classes.Duration(3, 58), "Pop", 1),
    classes.Song("Take My Breath", "The Weeknd", "Dawn FM", classes.Duration(5, 39), "Pop", 1),
    classes.Song("Don't Start Now", "Dua Lipa", "Future Nostalgia", classes.Duration(3, 3), "Pop", 1),
    classes.Song("Levitating", "Dua Lipa", "Future Nostalgia", classes.Duration(3, 23), "Pop", 1),
    classes.Song("New Rules", "Dua Lipa", "Dua Lipa", classes.Duration(3, 29), "Pop", 1),
    classes.Song("Physical", "Dua Lipa", "Future Nostalgia", classes.Duration(3, 13), "Pop", 1),
    classes.Song("Break My Heart", "Dua Lipa", "Future Nostalgia", classes.Duration(3, 37), "Pop", 1),
    classes.Song("Love Again", "Dua Lipa", "Future Nostalgia", classes.Duration(4, 18), "Pop", 1),
    classes.Song("Be the One", "Dua Lipa", "Dua Lipa", classes.Duration(3, 22), "Pop", 1),
    classes.Song("IDGAF", "Dua Lipa", "Dua Lipa", classes.Duration(3, 38), "Pop", 1),
    classes.Song("Hallucinate", "Dua Lipa", "Future Nostalgia", classes.Duration(3, 28), "Pop", 1),
    classes.Song("Cool", "Dua Lipa", "Future Nostalgia", classes.Duration(3, 30), "Pop", 1),
    classes.Song("Hotter Than Hell", "Dua Lipa", "Dua Lipa", classes.Duration(3, 7), "Pop", 1),
    classes.Song("Electricity", "Dua Lipa, Silk City", "Electricity", classes.Duration(3, 58), "Pop", 1),
    classes.Song("Future Nostalgia", "Dua Lipa", "Future Nostalgia", classes.Duration(3, 4), "Pop", 1),
    classes.Song("Pretty Please", "Dua Lipa", "Future Nostalgia", classes.Duration(3, 15), "Pop", 1),
    classes.Song("Lost in Your Light", "Dua Lipa, Miguel", "Dua Lipa", classes.Duration(3, 23), "Pop", 1),
    classes.Song("We're Good", "Dua Lipa", "Future Nostalgia (Moonlight Edition)", classes.Duration(2, 45), "Pop", 1),
    classes.Song("Blow Your Mind (Mwah)", "Dua Lipa", "Dua Lipa", classes.Duration(2, 58), "Pop", 1),
    classes.Song("No Lie", "Sean Paul, Dua Lipa", "No Lie", classes.Duration(3, 41), "Pop", 1),
    classes.Song("Dance the Night", "Dua Lipa", "Barbie Soundtrack", classes.Duration(2, 56), "Pop", 1),
    classes.Song("Training Season", "Dua Lipa", "Training Season", classes.Duration(3, 15), "Pop", 1),
    classes.Song("Uptown Funk", "Mark Ronson ft. Bruno Mars", "Uptown Special", classes.Duration(4, 30), "Funk", 1),
    classes.Song("Shape of You", "Ed Sheeran", "Divide", classes.Duration(3, 53), "Pop", 1),
    classes.Song("Rolling in the Deep", "Adele", "21", classes.Duration(3, 48), "Pop", 1),
    classes.Song("Old Town Road", "Lil Nas X ft. Billy Ray Cyrus", "7", classes.Duration(2, 37), "Country Rap", 1),
    classes.Song("Despacito", "Luis Fonsi ft. Daddy Yankee", "Vida", classes.Duration(3, 49), "Reggaeton", 1),
    classes.Song("Closer", "The Chainsmokers ft. Halsey", "Collage", classes.Duration(4, 4), "Electronic", 1),
    classes.Song("We Found Love", "Rihanna ft. Calvin Harris", "Talk That Talk", classes.Duration(3, 41), "Dance", 1),
    classes.Song("Take Me to Church", "Hozier", "Hozier", classes.Duration(4, 1), "Alternative", 1),
    classes.Song("Call Me Maybe", "Carly Rae Jepsen", "Kiss", classes.Duration(3, 13), "Pop", 1),
    classes.Song("Happy", "Pharrell Williams", "G I R L", classes.Duration(3, 53), "Pop", 1),
    classes.Song("Royals", "Lorde", "Pure Heroine", classes.Duration(3, 10), "Pop", 1),
    classes.Song("All of Me", "John Legend", "Love in the Future", classes.Duration(4, 30), "R&B", 1),
    classes.Song("Stay With Me", "Sam Smith", "In the Lonely Hour", classes.Duration(2, 52), "Pop", 1),
    classes.Song("Let It Go", "Idina Menzel", "Frozen Soundtrack", classes.Duration(3, 44), "Soundtrack", 1),
    classes.Song("Sorry", "Justin Bieber", "Purpose", classes.Duration(3, 20), "Pop", 1),
    classes.Song("God's Plan", "Drake", "Scorpion", classes.Duration(3, 18), "Hip-Hop", 1)
]



from collections import Counter

def find_duplicate_titles(songs):
    title_counts = Counter(song.title.strip().lower() for song in songs)
    duplicates = [title for title, count in title_counts.items() if count > 1]
    return duplicates

print(find_duplicate_titles(songs))








