import classes

songs = [
    classes.Song("Work From Home", "Fifth Harmony,Ty Dolla $ign", "7/27", classes.Duration(3, 44), "Pop", 2),
    classes.Song("Heartless", "The Weeknd", "After Hours", classes.Duration(3, 18), "Rap", 7),
    classes.Song("Hello", "Adele", "25", classes.Duration(4, 55), "Pop", 1),
    classes.Song("The Box", "Roddy Ricch", "Please Excuse Me for Being Antisocial", classes.Duration(3, 16), "Rap", 2),
    classes.Song("Rockstar", "Post Malone,21 Savage", "Beerbongs & Bentleys", classes.Duration(3, 38), "Rap", 1),
    classes.Song("Industry Baby", "Lil Nas X,Jack Harlow", "Montero", classes.Duration(3, 32), "Rap", 1),
    classes.Song("No Role Modelz", "J. Cole", "2014 Forest Hills Drive", classes.Duration(4, 53), "Rap", 2),
    classes.Song("Bohemian Rhapsody", "Queen", "A Night at the Opera", classes.Duration(5, 55), "Classic Rock", 1),
    classes.Song("Stairway to Heaven", "Led Zeppelin", "Led Zeppelin IV", classes.Duration(8, 2), "Classic Rock", 1),
    classes.Song("Hotel California", "Eagles", "Hotel California", classes.Duration(6, 30), "Classic Rock", 1),
    classes.Song("Imagine", "John Lennon", "Imagine", classes.Duration(3, 3), "Classic Rock", 2),
    classes.Song("Born to Run", "Bruce Springsteen", "Born to Run", classes.Duration(4, 30), "Classic Rock", 2),
    classes.Song("Smoke on the Water", "Deep Purple", "Machine Head", classes.Duration(5, 40), "Classic Rock", 3),
    classes.Song("Back in Black", "AC/DC", "Back in Black", classes.Duration(4, 15), "Classic Rock", 1),
    classes.Song("Bad Habits", "Ed Sheeran", "Equals", classes.Duration(3, 50), "Pop", 1),
    classes.Song("Shallow", "Lady Gaga,Bradley Cooper", "A Star Is Born", classes.Duration(3, 36), "Soundtrack", 2),
    classes.Song("Perfect", "Ed Sheeran", "Divide", classes.Duration(4, 23), "Pop",1),
    classes.Song("Thriller", "Michael Jackson", "Thriller", classes.Duration(5, 57), "Pop", 1),
    classes.Song("Hey Jude", "The Beatles", "Hey Jude", classes.Duration(7, 11), "Rock", 1),
    classes.Song("Like a Prayer", "Madonna", "Like a Prayer", classes.Duration(5, 38), "Pop", 1),
    classes.Song("Livin' on a Prayer", "Bon Jovi", "Slippery When Wet", classes.Duration(4, 9), "Rock", 1),
    classes.Song("Poker Face", "Lady Gaga", "The Fame", classes.Duration(3, 57), "Pop", 1),
    classes.Song("Rolling in the Deep", "Adele", "21", classes.Duration(3, 48), "Pop", 1),
    classes.Song("We Will Rock You", "Queen", "News of the World", classes.Duration(2, 2), "Rock", 1),
    classes.Song("Don't Stop Believin'", "Journey", "Escape", classes.Duration(4, 11), "Rock", 1),
    classes.Song("Dancing Queen", "ABBA", "Arrival", classes.Duration(3, 51), "Pop", 1),
    classes.Song("We Are the Champions", "Queen", "News of the World", classes.Duration(3, 0), "Rock", 1),
    classes.Song("Super Bass", "Nicki Minaj", "Pink Friday", classes.Duration(3, 20), "Hip-Hop", 1),
    classes.Song("Take on Me", "A-ha", "Hunting High and Low", classes.Duration(3, 45), "Synth-pop", 1),
    classes.Song("I Want to Hold Your Hand", "The Beatles", "Meet The Beatles!", classes.Duration(2, 24), "Rock", 1),
    classes.Song("Call Me Maybe", "Carly Rae Jepsen", "Kiss", classes.Duration(3, 13), "Pop", 1),
    classes.Song("Beat It", "Michael Jackson", "Thriller", classes.Duration(4, 18), "Pop", 1),
    classes.Song("Creep", "Radiohead", "Pablo Honey", classes.Duration(3, 56), "Alternative Rock", 1),
    classes.Song("Royals", "Lorde", "Pure Heroine", classes.Duration(3, 10), "Pop", 1),
    classes.Song("Stayin' Alive", "Bee Gees", "Saturday Night Fever", classes.Duration(4, 45), "Disco", 1),
    classes.Song("Take Me to Church", "Hozier", "Hozier", classes.Duration(4, 1), "Alternative", 1),
    classes.Song("Cheap Thrills", "Sia, Sean Paul", "This Is Acting", classes.Duration(3, 31), "Pop", 1),
    classes.Song("Somebody That I Used to Know", "Gotye, Kimbra", "Making Mirrors", classes.Duration(4, 5), "Alternative", 1),
    classes.Song("Shake It Off", "Taylor Swift", "1989", classes.Duration(3, 39), "Pop", 1),
    classes.Song("Bohemian Rhapsody", "Queen", "A Night at the Opera", classes.Duration(5, 55), "Classic Rock", 1),
    classes.Song("Radioactive", "Imagine Dragons", "Night Visions", classes.Duration(3, 6), "Alternative Rock", 1),
    classes.Song("All Star", "Smash Mouth", "Astro Lounge", classes.Duration(3, 21), "Alternative Rock", 1),
    classes.Song("Counting Stars", "OneRepublic", "Native", classes.Duration(4, 17), "Pop", 1),
    classes.Song("I Will Always Love You", "Whitney Houston", "The Bodyguard Soundtrack", classes.Duration(4, 31), "Pop", 1),
    classes.Song("Can't Stop the Feeling!", "Justin Timberlake", "Trolls Soundtrack", classes.Duration(3, 56), "Pop", 1),
    classes.Song("Sweet Home Alabama", "Lynyrd Skynyrd", "Second Helping", classes.Duration(4, 45), "Classic Rock", 1),
    classes.Song("Born to Run", "Bruce Springsteen", "Born to Run", classes.Duration(4, 30), "Classic Rock", 1),
    classes.Song("Take Me Home, Country Roads", "John Denver", "Poems, Prayers & Promises", classes.Duration(3, 10), "Country", 1),
    classes.Song("Boulevard of Broken Dreams", "Green Day", "American Idiot", classes.Duration(4, 20), "Alternative Rock", 1),
    classes.Song("Dream On", "Aerosmith", "Aerosmith", classes.Duration(4, 28), "Classic Rock", 1),
    classes.Song("Summer of '69", "Bryan Adams", "Reckless", classes.Duration(3, 36), "Rock", 1),
    classes.Song("Wonderwall", "Oasis", "(What's the Story) Morning Glory?", classes.Duration(4, 18), "Britpop", 1),
    classes.Song("Smells Like Teen Spirit", "Nirvana", "Nevermind", classes.Duration(5, 1), "Grunge", 1),
    classes.Song("Seven Nation Army", "The White Stripes", "Elephant", classes.Duration(3, 52), "Alternative Rock", 1),
    classes.Song("Hallelujah", "Jeff Buckley", "Grace", classes.Duration(6, 53), "Alternative", 1),
    classes.Song("Shallow", "Lady Gaga, Bradley Cooper", "A Star Is Born", classes.Duration(3, 36), "Soundtrack", 2),
    classes.Song("Mr. Brightside", "The Killers", "Hot Fuss", classes.Duration(3, 43), "Alternative Rock", 1),
    classes.Song("Heroes", "David Bowie", "Heroes", classes.Duration(6, 7), "Rock", 1),
    classes.Song("Sweet Child O' Mine", "Guns N' Roses", "Appetite for Destruction", classes.Duration(5, 56), "Classic Rock", 1),
    classes.Song("I Wanna Dance with Somebody", "Whitney Houston", "Whitney", classes.Duration(4, 51), "Pop", 1),
    classes.Song("Can't Help Falling in Love", "Elvis Presley", "Blue Hawaii", classes.Duration(3, 0), "Classic Rock", 1),
    classes.Song("California Love", "2Pac, Dr. Dre", "All Eyez on Me", classes.Duration(5, 46), "Hip-Hop", 1),
    classes.Song("Iris", "Goo Goo Dolls", "Dizzy Up the Girl", classes.Duration(4, 50), "Alternative Rock", 1),
    classes.Song("Africa", "Toto", "Toto IV", classes.Duration(4, 55), "Rock", 1),
    classes.Song("Eye of the Tiger", "Survivor", "Rocky III Soundtrack", classes.Duration(4, 5), "Rock", 1),
    classes.Song("Let It Be", "The Beatles", "Let It Be", classes.Duration(4, 3), "Rock", 1),
    classes.Song("Riptide", "Vance Joy", "Dream Your Life Away", classes.Duration(3, 24), "Indie", 1),
    classes.Song("Chasing Cars", "Snow Patrol", "Eyes Open", classes.Duration(4, 27), "Alternative Rock", 1),
    classes.Song("American Idiot", "Green Day", "American Idiot", classes.Duration(2, 54), "Punk Rock", 1),
    classes.Song("Lose Yourself", "Eminem", "8 Mile Soundtrack", classes.Duration(5, 20), "Hip-Hop", 1),
    classes.Song("Let It Go", "Idina Menzel", "Frozen Soundtrack", classes.Duration(3, 44), "Soundtrack", 1),
    classes.Song("Bad Guy", "Billie Eilish", "When We All Fall Asleep, Where Do We Go?", classes.Duration(3, 14), "Pop", 1),
    classes.Song("Clocks", "Coldplay", "A Rush of Blood to the Head", classes.Duration(5, 7), "Alternative Rock", 1),
    classes.Song("Wake Me Up", "Avicii", "True", classes.Duration(4, 7), "Electronic", 1),
    classes.Song("The Sound of Silence", "Simon & Garfunkel", "Wednesday Morning, 3 A.M.", classes.Duration(3, 5), "Folk Rock", 1),
    classes.Song("Paint It Black", "The Rolling Stones", "Aftermath", classes.Duration(3, 22), "Rock", 1),
    classes.Song("Happy", "Pharrell Williams", "G I R L", classes.Duration(3, 53), "Pop", 1),
    classes.Song("Lose Control", "Teddy Swims", "Lose Control", classes.Duration(3, 30), "Pop", 1),
    classes.Song("Espresso", "Sabrina Carpenter", "Espresso", classes.Duration(2, 50), "Pop", 1),
    classes.Song("I Had Some Help", "Post Malone, Morgan Wallen", "I Had Some Help", classes.Duration(3, 20), "Country", 1),
    classes.Song("Too Sweet", "Hozier", "Unreal Unearth", classes.Duration(4, 10), "Alternative", 1),
    classes.Song("Greedy", "Tate McRae", "Greedy", classes.Duration(2, 45), "Pop", 1),
    classes.Song("Paint the Town Red", "Doja Cat", "Scarlet", classes.Duration(3, 51), "Hip-Hop", 1),
    classes.Song("Fortnight", "Taylor Swift, Post Malone", "The Tortured Poets Department", classes.Duration(3, 45), "Pop", 1),
    classes.Song("Birds of a Feather", "Billie Eilish", "Hit Me Hard and Soft", classes.Duration(3, 55), "Pop", 1),
    classes.Song("Million Dollar Baby", "Tommy Richman", "Million Dollar Baby", classes.Duration(3, 10), "Pop", 1),
    classes.Song("Good Luck, Babe!", "Chappell Roan", "Good Luck, Babe!", classes.Duration(3, 40), "Pop", 1),
    classes.Song("Saturn", "SZA", "Saturn", classes.Duration(3, 30), "R&B", 1),
    classes.Song("Fast Car", "Luke Combs", "Fast Car", classes.Duration(4, 0), "Country", 1),
    classes.Song("Water", "Tyla", "Tyla", classes.Duration(3, 20), "Afrobeats", 1),
    classes.Song("Feather", "Sabrina Carpenter", "Feather", classes.Duration(2, 55), "Pop", 1),
    classes.Song("Not Like Us", "Kendrick Lamar", "Not Like Us", classes.Duration(4, 30), "Hip-Hop", 1),
    classes.Song("Please Please Please", "Sabrina Carpenter", "Please Please Please", classes.Duration(3, 15), "Pop", 1),
    classes.Song("Agora Hills", "Doja Cat", "Scarlet", classes.Duration(4, 20), "Hip-Hop", 1),
    classes.Song("I Remember Everything", "Zach Bryan, Kacey Musgraves", "I Remember Everything", classes.Duration(3, 50), "Country", 1),
    classes.Song("Lovin on Me", "Jack Harlow", "Lovin on Me", classes.Duration(2, 30), "Hip-Hop", 1),
    classes.Song("Thinkin' Bout Me", "Morgan Wallen", "Thinkin' Bout Me", classes.Duration(3, 45), "Country", 1)
]



